version: '3.8'  

services:

  user-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: mada
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  chat-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: mada
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chats_db
    ports:
      - "5434:5432"
    volumes:
      - chat-db-data:/var/lib/postgresql/data

  chat-service:
    build:
      context: .
      dockerfile: dockerfile.chat
    image: umadmary/pad-1:chat-service 
    ports:
      - "5001"
    deploy:
      replicas: 2  

  user-service:
    build:
      context: .
      dockerfile: dockerfile.user
    image: umadmary/pad-1:user-service
    ports:
      - "5002"
    deploy:
      replicas: 2 

  api-gateway:
    build:
      context: .
      dockerfile: dockerfile.api
    image: umadmary/pad-1:api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - chat-service
      - user-service

  prometheus:
    image: prom/prometheus:v2.19.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
      
volumes:
  user-db-data:
  chat-db-data:
  prometheus_data: 
  grafana_data: