version: '3'

services:
  chat-service:
    build:
      context: .
      dockerfile: dockerfile.chat
    container_name: chat-service
    ports:
      - "5001:5001"

  user-service:
    build:
      context: .
      dockerfile: dockerfile.user
    container_name: user-service
    ports:
      - "5002:5002"

  api-gateway:
    build:
      context: .
      dockerfile: dockerfile.api
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - chat-service
      - user-service
