version: '3'

services:
  chat-service:
    build:
        context: .
        dockerfile: dockerfile.chat
    image: chat-service:latest  
    container_name: chat-service
    ports:
      - "5001:5001"
    volumes:
      - ./chats.db:/app/chats.db

  user-service:
    build:
        context: .
        dockerfile: dockerfile.user
    image: user-service:latest  
    container_name: user-service
    ports:
      - "5002:5002"
    volumes:
      - ./users.db:/app/users.db

  api-gateway:
    build:
        context: .
        dockerfile: dockerfile.api
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - chat-service
      - user-service

