global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: api-gateway
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - api-gateway:3000
  
